<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN522769" failures="0" tests="5" name="Default test" time="3.757" errors="0" timestamp="2025-01-22T12:48:11 IST">
  <testcase classname="hackthon.Hack1" name="@BeforeClass setUp" time="3.698">
    <failure type="java.lang.NullPointerException" message="Cannot load from object array because &amp;quot;this.data&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot load from object array because "this.data" is null
at hackthon.Hack1Methods.initializeDriver(Hack1Methods.java:52)
at hackthon.Hack1.setUp(Hack1.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- @BeforeClass setUp -->
  <testcase classname="hackthon.Hack1" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="hackthon.Hack1" name="testScrollAndClickBookshelves" time="0.001">
    <skipped/>
  </testcase> <!-- testScrollAndClickBookshelves -->
  <testcase classname="hackthon.Hack1" name="testHandlePriceSlider" time="0.0">
    <skipped/>
  </testcase> <!-- testHandlePriceSlider -->
  <testcase classname="hackthon.Hack1" name="testExtractBookshelves" time="0.0">
    <skipped/>
  </testcase> <!-- testExtractBookshelves -->
  <testcase classname="hackthon.Hack1" name="testRetrieveSubMenuItems" time="0.0">
    <skipped/>
  </testcase> <!-- testRetrieveSubMenuItems -->
  <testcase classname="hackthon.Hack1" name="testCaptureErrorMessage" time="0.0">
    <skipped/>
  </testcase> <!-- testCaptureErrorMessage -->
</testsuite> <!-- Default test -->
